### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by ChristopherJTrent** [acheung-94/pet-portal#74]
- [x] Add a bit of padding-left to the fields on the edit/delete reminder form. it looks a bit cramped
- [x] align the edit pop-in text with the other text on the list elements
- [x] change the time format on reminders to remove the leading 0 on 1-digit hours
- [x] change the color of the close button on the edit form from white to black
- [x] increase the font size on the '* required' nag
- [x] replace the asterisk on the '* required' nag with an interpunct '·'
- [x] add edit and delete button
- [x] change reminder modal to just be an edit reminder modal

**Comment by sam-kim99** [comment]
implemented in enhancement/touch up reminders
