### ISSUE TITLE
401 after logging in

### ISSUE THREAD

**Issue by acheung-94** [acheung-94/pet-portal#87]
- [ ] initially after logging in, can't issue any crud actions and get 401 on invalid csrf token. But if you refresh the page and hit the csrf/restore endpoint again, then it'll work after that.

**Comment by ChristopherJTrent** [comment]
This issue is going to be related to how the frontend is handling CSRF tokens.
the CSRF restore endpoint doesn't exist on prod.

**Comment by ChristopherJTrent** [comment]
resolved by #89
